#!/usr/bin/env python3.10
from coordinates import get_gps_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather
from exceptions import ApiServiceError, CantGetCoordinates

def main():
    try:
        coordinates = get_gps_coordinates()
    except CantGetCoordinates:
        print("Не удалось получить GPS координаты")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print("Не удалось получить погоду по координатам")
        exit(1)
    print(format_weather(weather))

if __name__ == "__main__":
    main()



